
#' new_travel_blog
#'
#' Create a new travel blog
#'
#' @import fs
#'
#' @param path target directory where to put the new blog
#' @param ... template input rstudio
#'

new_travel_blog <-function(path, ...){
  # ensure path exists
  dir.create(path, recursive = TRUE, showWarnings = FALSE)

  # generate header for file
  header <- c(
    "# This file was generated by a call to 'tripdown::new_travel_blog()'.",
    "# You have just created a new blog:",
    ""
  )

  # collect inputs and paste together as 'Parameter: Value'
  dots <- list(...)
  text <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val)
  })

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    sep = "\n"
  )

  # write to index file
  writeLines(contents, con = file.path(path, "INDEX"))


  # copy the blog structure into the path
  source_directory <- system.file("blog", package = "tripdown")
  dir_copy(source_directory, path)


}
